<?php /** @var matpoppl\SmallMVC\View\ViewData $view */ $view->extends('modules:cron/views/layout.phtml') ?>

<form method="post">
	<button type="submit" hidden>neutral button must be first</button>
<table border="1">
	<caption style="caption-side: bottom;">
		<div style="display:flex">
		<select name="action">
			<option value=""><?= $view->translate('-- Modify selected --') ?></option>
			<option value="delete"><?= $view->translate('Delete') ?></option>
		</select>
		<button type="submit" class="btn btn--primary"><?= $view->translate('Modify selected') ?></button>
		</div>
	</caption>
	<thead>
		<tr>
			<th><?= $view->translate('ID') ?></th>
			<th><?= $view->translate('Name') ?></th>
			<th><?= $view->translate('Run') ?></th>
			<th><?= $view->translate('Triggers') ?></th>
			<th><?= $view->translate('Modify') ?></th>
		</tr>
	</thead>
	<tbody>
<?php foreach($view['rows'] as $r): ?>
		<tr>
			<th><input type="checkbox" name="id[]" value="<?= $r['id'] ?>" /></th>
			<td><a href="<?= $view->route('task/edit', ['id' => $r['id'] ]) ?>"><?= $r['name'] ?></a></td>
			<td><a href="<?= $view->route('task/run', ['id' => $r['id'] ]) ?>">[run]</a></td>
			<td><a href="<?= $view->route('task/triggers', ['task_id' => $r['id'] ]) ?>">[triggers]</a></td>
			<td>
				<a href="<?= $view->route('task/edit', ['id' => $r['id'] ]) ?>">[edit]</a>
				&mdash;
				<button type="submit" name="id[]" value="<?= $r['id'] ?>" formaction="<?= $view->route('task/del') ?>">delete</button>
			</td>
		</tr>
<?php endforeach; ?>
	</tbody>
</table>
<input type="hidden" name="csrf" value="<?= $view['csrfHash'] ?>" />
</form>