version: '3.1'

services:
  server-dev:
    build:
      context: .
    ports:
      - 35729:35729
      - 8081:8081
    environment: 
      - LIVERELOAD_HOST=0.0.0.0
      - LIVERELOAD_PORT=35729
      - DEV_ASSETS_HOST=0.0.0.0
      - DEV_ASSETS_PORT=8081
    networks:
      - pubnet
    volumes:
      - ./:/var/www/html/_dev
    command: npm run dev

networks:
  pubnet:
